api_id: 0
api_hash: ""
session: data/session
log_level: info
instances:
  - name: default
    entities:
      - https://t.me/tboom_66
    folders: []
    words: ["my username"]
    target_chat: 0
    target_entity: ""
