api_id: 0
api_hash: ""
session: data/session
log_level: info
openai_api_key: ""
openai_model: gpt-4.1-mini
langfuse_public_key: ""
langfuse_secret_key: ""
langfuse_base_url: ""
ignore_usernames: []
instances:
  - name: default
    entities:
      - https://t.me/tboom_66
    folders: []
    folder_mute: false
    words: ["my username"]
    ignore_words: []
    prompts:
      - name: example
        prompt: Сообщение содержит недовольство.
        threshold: 4
    target_chat: 0
    target_entity: ""
    false_positive_entity: ""
    true_positive_entity: ""
