api_id: 0
api_hash: ""
session: data/session
log_level: info
openai_api_key: ""
openai_model: gpt-4.1-mini
langfuse_public_key: ""
langfuse_secret_key: ""
langfuse_base_url: ""
ignore_usernames: []
ignore_user_ids: []
instances:
  - name: default
    entities:
      - https://t.me/tboom_66
    folders: []
    folder_mute: false
    no_forward_message: false
    words: ["my username"]
    negative_words: []
    ignore_words: []
    prompts:
      - name: example
        prompt: Сообщение содержит недовольство.
        threshold: 4
        # Uncomment to load prompt text from Langfuse
        # langfuse_name: movie-critic
        # langfuse_label: production
        # langfuse_version: 1
        # langfuse_type: text
        # config:
        #   model: gpt-4o
        #   temperature: 0.7
    target_chat: 0
    target_entity: ""
    false_positive_entity: ""
    true_positive_entity: ""
